name: test

on:
  push:
    branches:
      - main
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update npm to latest version
        run: npm install --global npm@latest

      - name: Test poseidon-deployer
        run: |
          npm install
          npm run build
          npm run test
        working-directory: devops/poseidon-deployer
